#
# R script for making a SEG file from an output of qdnaseq.R
#
# Masashi Fujita (m-fujita@riken.jp), Dec. 19, 2018
#
# To run this script, "tidyverse" and "data.table" packages are required.
#
# Usage: Rscript make-seg.R <tumor sample ID> \
#           <tumor.tsv generated by qdnaseq.R> <output SEG>
#

library(tidyverse)
library(data.table)

#
# parse command args
#
args <- commandArgs(trailingOnly=T)
sample_id <- args[1]
inseg_file <- args[2]
outseg_file <- args[3]

inseg <- fread(inseg_file, data.table=F)

get_seg_boundary <- function(df){
  df <- df %>%
    rename(cn=5) %>%
    mutate(row_id=as.numeric(rownames(df)))

  seg_len <- df$cn %>% unlist %>% unname %>% rle %>% .$length
  cum_seg_len <- cumsum(seg_len)

  seg_pos <- data.frame(
    row_id_from=shift(cum_seg_len, fill=0) + 1,
    row_id_to=cum_seg_len
  )

  seg <- seg_pos %>%
    inner_join(df, by=c("row_id_from"="row_id")) %>%
    inner_join(df, by=c("row_id_to"="row_id"), suffix=c(".from", ".to"))

  if(any(seg$cn.from != seg$cn.to)) {
    stop("[ERROR] cn mismatch")
  }
  if(any(seg$start.from > seg$start.to)) {
    stop("[ERROR] start inconsistency")
  }
  if(any(seg$end.from > seg$end.to)) {
    stop("[ERROR] end inconsistency")
  }
  seg <- seg %>%
    mutate(Num.SNPs=row_id_to - row_id_from + 1) %>%
    select(start.from, end.to, Num.SNPs, cn.to) %>%
    rename(Start.bp=start.from, End.bp=end.to, Seg.CN=cn.to)

  return(seg)
}

res <- inseg %>%
  group_by(chromosome) %>%
  do(get_seg_boundary(.)) %>%
  ungroup %>%
  rename(Chromosome=chromosome)

res <- data.frame(Sample=sample_id, res)
res %>% write_tsv(outseg_file)
